id="ttera-themes"
name="ttera themes"
version="1.0.0"
schema_version=1
authors=["Alec Zhou alec1.zhou@gmail.com"]
description="21 themes modeled off of nature, media, and aesthetic. Contact me to inquire about edits, fixes, or additions"
respository="https://github.com/azhou555/ttera-themes"
